# Generated by Django 5.2.11 on 2026-02-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('hot_rank', models.IntegerField(blank=True, null=True)),
                ('source', models.IntegerField()),
                ('batch_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '新闻文章',
                'verbose_name_plural': '新闻文章',
                'db_table': 'ranking',
                'ordering': ['hot_rank'],
                'indexes': [models.Index(fields=['source', 'batch_timestamp'], name='ranking_source_d47265_idx'), models.Index(fields=['source', 'hot_rank'], name='ranking_source_0c99e5_idx')],
            },
        ),
    ]
