# Generated by Django 5.2.11 on 2026-02-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['source', '-batch_timestamp', 'hot_rank'], name='idx_src_batch_rank'),
        ),
    ]
